---
- include_role:
    name: app-unguard

- include_role:
    name: app-simplenode
  vars:
    git_username: "{{ gitea_username }}"
    git_password: "{{ gitea_password }}"
    git_domain: "{{ gitea_domain }}"
    git_remote: "gitea"
    git_org_name: "{{ demo_appsec_org }}"
    repo_name: "{{ demo_appsec_repo_name }}"
  when: new_repo_created is defined and new_repo_created == true

- set_fact:
    include_jenkins_value_file: "{{ role_path }}/templates/hot-appsec-jobs.yml.j2"


- file:
    path: "/home/{{ ace_box_user }}/ansible/roles/dashboard/files/helm-values"
    state: directory
    
- include_role:
    name: dashboard


