apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-proxy-service"
  labels:
    app.kubernetes.io/name: proxy-service
    app.kubernetes.io/part-of: "{{ .Chart.Name }}"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: proxy-service
    app.kubernetes.io/part-of: "{{ .Chart.Name }}"
  ports:
    - targetPort: 8081
      port: 80
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: unguard-proxy
  labels:
    app.kubernetes.io/name: proxy-service
    app.kubernetes.io/part-of: {{ .Chart.Name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: proxy-role
  labels:
    app.kubernetes.io/name: proxy-service
    app.kubernetes.io/part-of: {{ .Chart.Name }}
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods"]
    verbs: ["create", "list", "get"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: proxy-rolebinding
  labels:
    app.kubernetes.io/name: proxy-service
    app.kubernetes.io/part-of: {{ .Chart.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Chart.Name }}-proxy
    apiGroup: ""
roleRef:
  kind: Role
  name: proxy-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}-proxy-service"
  labels:
    app.kubernetes.io/name: proxy-service
    app.kubernetes.io/component: proxy-service
    app.kubernetes.io/version: "{{ .Values.unguard.proxyService.tag }}"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/part-of: "{{ .Chart.Name }}"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: proxy-service
      app.kubernetes.io/part-of: "{{ .Chart.Name }}"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: proxy-service
        app.kubernetes.io/part-of: "{{ .Chart.Name }}"
    spec:
      containers:
        - name: proxy-service
          image: "{{ .Values.unguard.proxyService.image }}:{{ .Values.unguard.proxyService.tag }}"
          ports:
            - containerPort: 8081
          env:
            - name: SERVER_PORT
              value: "8081"
            - name: JAEGER_SERVICE_NAME
              value: "{{ .Chart.Name }}-proxy-service"
            - name: JAEGER_AGENT_HOST
              value: "jaeger-agent" # change depending on your jaeger deployment
            - name: JAEGER_SAMPLER_TYPE
              value: "const"
            - name: JAEGER_SAMPLER_PARAM
              value: "1"
            - name: DT_RELEASE_VERSION
              value: "{{ .Values.unguard.proxyService.tag }}"
            - name: DT_RELEASE_BUILD_VERSION
              value: "{{ .Values.unguard.proxyService.tag }}"
            - name: DT_RELEASE_PRODUCT
              value: "{{ .Chart.Name }}"
            - name: DT_RELEASE_STAGE
              value: "{{ .Release.Namespace }}"
