config:
    - unguard-http: "unguard-http.json"
    - unguard-clickpath: "unguard-clickpath.json"
  
unguard-http:
    - name: "unguard.http"
    - url: "http://unguard.{{ .Env.INGRESS_DOMAIN }}/ui"
    - description: "HTTP Monitor for unguard"
    - location: "/base/synthetic-location/acebox.id"
    - managementZoneId: "/base/management-zone/unguard.id"
    - tag: "unguard"
    - applicationId: "/base/application/app-unguard.id"
    - enabled: "true"

unguard-clickpath:
    - name: "unguard.clickpath"
    - url: "http://unguard.{{ .Env.INGRESS_DOMAIN }}/ui"
    - description: "ClickPath for unguard"
    - location: "/base/synthetic-location/acebox.id"
    - managementZoneId: "/base/management-zone/unguard.id"
    - tag: "unguard"
    - applicationId: "/base/application/app-unguard.id"
    - enabled: "true"