apiVersion: apps/v1
kind: Deployment
metadata:
  name: unguard-malicious-load-generator
  labels:
    app.kubernetes.io/name: malicious-load-generator
    app.kubernetes.io/part-of: unguard
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: malicious-load-generator
      app.kubernetes.io/part-of: unguard
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: malicious-load-generator
        app.kubernetes.io/part-of: unguard
    spec:
      terminationGracePeriodSeconds: 5
      restartPolicy: Always
      containers:
        - name: malicious-load-generator
          image: unguard-malicious-load-generator
          env: # could add here run time as well
            - name: FRONTEND_ADDR
              value: "unguard-frontend:80/ui"
              # USERS and WAIT_TIME (in seconds) are optional, default value for USERS = 1, WAIT_TIME = 1800
            - name: USERS
              value: "1"
            - name: WAIT_TIME
              value: "1800"
      initContainers:
        - name: wait-for-frontend
          image: curlimages/curl
          command: ["/bin/sh", "-c"]
          # CASP-8983 replace this endpoint with a proper health check endpoint
          args: [ 'while [ $(curl -ksw "%{http_code}" "http://unguard-frontend:80/ui/img/logo.svg" -o /dev/null) -ne 200 ]; do sleep 5; echo "health check failed . Waiting for the service..."; done' ]

