apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../ingress
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.2.1/deploy/static/provider/kind/deploy.yaml

# make this the default ingress class so that we don't have to annotate it explicitly
# see https://kubernetes.github.io/ingress-nginx/#i-have-only-one-ingress-controller-in-my-cluster-what-should-i-do
patchesStrategicMerge:
  - |-
    apiVersion: networking.k8s.io/v1
    kind: IngressClass
    metadata:
      name: nginx
      annotations:
        ingressclass.kubernetes.io/is-default-class: "true"

# temporary workaround until ingress-nginx#7118 is resolved
# see https://github.com/kubernetes/ingress-nginx/issues/7118
patches:
  - target:
      kind: Job
    patch: |-
      - op: add
        path: /spec/ttlSecondsAfterFinished
        value: 0
