apiVersion: v1
kind: Service
metadata:
  name: unguard-envoy-proxy
  labels:
    app.kubernetes.io/name: envoy-proxy
    app.kubernetes.io/part-of: unguard
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: envoy-proxy
    app.kubernetes.io/part-of: unguard
  ports:
    - name: http
      targetPort: 8080
      port: 8080
    - name: health
      targetPort: 8081
      port: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unguard-envoy-proxy
  labels:
    app.kubernetes.io/name: envoy-proxy
    app.kubernetes.io/part-of: unguard
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: envoy-proxy
      app.kubernetes.io/part-of: unguard
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: envoy-proxy
        app.kubernetes.io/part-of: unguard
    spec:
      containers:
        - name: envoy-proxy
          image: unguard-envoy-proxy
          ports:
            - name: http
              containerPort: 8080
            - name: health
              containerPort: 8081
