delete: 
    - "app-detection-rule/unguard"
    - "application-web/unguard"
    - "auto-tag/app"
    - "auto-tag/environment"
    - "management-zone/unguard"
    - "conditional-naming-processgroup/ACE Box - containername.namespace"
    - "conditional-naming-processgroup/Java Springboot Naming"
    - "conditional-naming-processgroup/MongoDB Naming"
    - "conditional-naming-processgroup/NodeJS Naming"
    - "conditional-naming-processgroup/Postgres Naming"
    - "conditional-naming-processgroup/ {ProcessGroup:ExeName} {ProcessGroup:KubernetesBasePodName}"
    - "conditional-naming-service/app.environment"
    - "dashboard/Application Security Issues"
    - "synthetic-location/ACE-BOX"
    - "synthetic-monitor/unguard.http"
    - "synthetic-monitor/unguard.clickpath"
    - "kubernetes-credentials/ACE-BOX"