apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: unguard
resources:
  - ../base
  - ingress.yaml
patchesStrategicMerge:
  # aws-load-balancer-controller only supports NodePort or LoadBalancer service types
  # https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/ingress/annotations/#traffic-routing
  - |-
    apiVersion: v1
    kind: Service
    metadata:
      name: unguard-envoy-proxy
    spec:
      type: NodePort
