apiVersion: apps/v1
kind: Deployment
metadata:
  name: unguard-frontend
spec:
  template:
    spec:
      containers:
        - name: frontend
          env:
            - name: JAEGER_SAMPLER_PARAM
              value: "1"
            - name: JAEGER_DISABLED
              value: "false"
