apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: unguard
resources:
  - ../base
patchesStrategicMerge:
  - microblog-service.yaml
  - proxy-service.yaml
  - ad-service.yaml
  - profile-service.yaml
  - user-auth-service.yaml
  - frontend.yaml
