apiVersion: apps/v1
kind: Deployment
metadata:
  name: unguard-proxy-service
spec:
  template:
    spec:
      serviceAccountName: unguard-proxy
      containers:
        - name: proxy-service
          env:
            - name: OPENTRACING_JAEGER_ENABLED
              value: "true"
            - name: JAEGER_SERVICE_NAME
              value: "unguard-proxy-service"
            - name: JAEGER_AGENT_HOST
              value: "jaeger-agent" # change depending on your jaeger deployment
            - name: JAEGER_SAMPLER_TYPE
              value: "const"
            - name: JAEGER_SAMPLER_PARAM
              value: "1"
