apiVersion: apps/v1
kind: Deployment
metadata:
  name: unguard-user-auth-service
spec:
  template:
    spec:
      containers:
        - name: user-auth-service
          env:
            - name: JAEGER_SAMPLER_PARAM
              value: "1"
            - name: JAEGER_DISABLED
              value: "false"
